### ISSUE TITLE
Avoid source copy hacks in Aven Tools

### ISSUE THREAD

**Issue by ericvicenti** [AvenCloud/Aven#14]
The tooling currently will copy source files to another app directory when it runs. This is a hack that allows me to avoid webpack/metro configuration, but the real solution is to configure these packagers to run in the monorepo and serve multiple apps correctly. Either by using one dev server for several apps (would be possible with metro), or by allowing multiple dev servers to share the same codebase while running.

**Comment by cinderblock** [comment]
Ultimately I think a single dev server is the best option as it can streamline the file watching and needs to be rebuilt. Could be configured to run some parts on remote systems, while still watching file changes locally.

The API/interface for this could be decided first even if behind the scenes it's hacky and doing extra copies/processes/watchers.

**Comment by ericvicenti** [comment]
Absolutely. Would you be able to help make a custom webpack config for running locally, instead of razzle? I can try to do the same with the metro/react native environment
